name: cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: cover
        ignore:
          - "**/dotnet-js-interop.ts"
        run: |
          dotnet test DotNet/DotNetJS.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          cd JavaScript/dotnet-runtime
          npm ci
          npm run build
          dotnet publish test/csharp/Test.sln
          npm install -g codecov
          npm install -g nyc
          nyc --reporter=lcov -x **/native -x **/bin -x **/dotnet-js-interop.ts npm run test
          cd ../..
          codecov
